#cloud-config
debug: true

cloud_init_modules:
  - migrator
  - seed_random
  - write-files
  - growpart
  - resizefs
  - set_hostname
  - update_hostname
  - update_etc_hosts
  - users-groups
  - ssh
  - runcmd

users:
  - name: user
    groups: sudo
    lock_passwd: false
    passwd: $6$rounds=4096$randomsalt$randomhashedpassword
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    shell: /bin/bash

chpasswd:
  list:
    - "user:user"
  expire: false

timezone: "Europe/Moscow"
fqdn: "postgres"

runcmd:
  - mkdir -p /opt/postgres
  - git clone https://github.com/logarifmdesiatichnyi/cloudMephi.git /opt/postgres
  - chmod -R 777 /opt/postgres
  - bash /opt/postgres/install_postgres.sh -i
